# Generated by Django 5.0.6 on 2024-05-27 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bank_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='banks', to=settings.AUTH_USER_MODEL),
        ),
    ]
