# Generated by Django 5.0.6 on 2024-05-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bank_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='routing_number',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='bank',
            name='swift_bic',
            field=models.CharField(max_length=11),
        ),
    ]
