# Generated by Django 5.0.6 on 2024-05-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
